### ISSUE TITLE
What's the license for this project?

### ISSUE THREAD

**Issue by sadreck** [MagicMau/ProceduralNameGenerator#1]
Hi,

I'd like to use the name generator in a project and was wondering what the license for it is, as there's no license file in the repo?

Thanks,
Pavel

**Comment by MagicMau** [comment]
Hi Pavel,

Consider it the MIT license. And cool that you’d like to use it!

Best regards,
Maurits

**Comment by sadreck** [comment]
I found the original project https://github.com/Tw1ddle/markov-namegen-lib and thought "gonna be a pain to port to C#" and was extremely happy when I saw you've already done it!

Outstanding work btw, thank you!

**Comment by sadreck** [comment]
Hey Maurits,

In case you were curious about where this code has been used, I've released Codecepticon at https://github.com/Accenture/Codecepticon

Thanks again!
Pavel
